### ISSUE TITLE
Package not up to date with the listings package

### ISSUE THREAD

**Issue by Timmyfox** [ho-tex/listingsutf8#2]
Since the last update to this package on CTAN, the listings package has seen several updates to provide various fixes and improvements. Unfortunately, this package has not yet been updated to regain parity.

**Comment by davidcarlisle** [comment]
You have provided no test file nor said what issue you are having. This package does not  re-implement any of the `listings` package it is simply a small wrapper handling encoding that then uses whatever version of `listings` you have, so it does not normally need to "regain parity": it simply uses the current listings package. 

If an incompatibility with current versions has arisen please open an issue with a test file and log.

**Comment by Timmyfox** [comment]
Understood, in that case there is no issue.
